### ISSUE TITLE
Mobs becoming invincible

### ISSUE THREAD

**Issue by Mocorongo** [thetrueoneshots/CubeMegaMod#2]
playing with this mod some **enemy mobs** can become invincible and to solve the problem temporarily I have to close the game and open it again, but after some time the same problem occurs again! 
I'm using the updated version of the mod and it happened with the old version too!

**Comment by thetrueoneshots** [comment]
Thanks for bringing it to my attention! This is most likely due to cubeworld overwriting id's of certain creatures... I hope to have it improved a bit by next update tomorrow. If it then still occurs, I will put more time into finding a fix to this bug. 

For now you can try going out of the water, to delete all the spawned underwater creates. I hope that at least helps a bit :)

**Comment by thetrueoneshots** [comment]
I fixed this bug with v1.3.0. You can find it under the releases. Thanks for notifying me. Do not hesitate to make issues for cool new ideas as well :)
